name: SuperKart MLOps Pipeline

on:
  push:
    branches:
      - main

jobs:

# -----------------------------
# 1. VALIDATE PROJECT STRUCTURE
# -----------------------------
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Check backend script
        run: |
          python -m py_compile data/backend_sources/superkart_sales_app.py

      - name: Check frontend script
        run: |
          python -m py_compile data/frontend_sources/superkart_sales_app_ui.py


# -----------------------------
# 2. TEST MODEL LOAD
# -----------------------------
  model-check:
    needs: validate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Test model loading
        run: |
          python -c "import joblib; joblib.load('data/backend_sources/superkart_sales_forecast_model.joblib')"


# -----------------------------
# 3. DEPLOY FRONTEND TO HF
# -----------------------------
  deploy-frontend:
    needs: [validate, model-check]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Hugging Face Hub
        run: |
          pip install huggingface_hub

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python -c "
from huggingface_hub import HfApi
api = HfApi(token='$HF_TOKEN')
api.upload_folder(
    repo_id='Lasya679/SuperKartSalesFrontend',
    folder_path='data/frontend_sources',
    repo_type='space'
)
"
